export type {
  Gender,
  Element,
  Polarity,
  LuckyLevel,
  Status,
  Frame,
  Energy,
  FourFrame,
  BirthInfo,
  NameBlock,
  NameCombination,
  NameQuery,
  ResolvedName,
  NameInput,
  EvaluateRequest,
  SearchRequest,
  FrameInsight,
  Interpretation,
  NameStatistics,
  SeedResponse,
  SearchResult,
  SeedTsUserInfo,
  SeedTsCandidate,
  SeedTsResult,
} from "../internal/seed-core.js";

