/**
 * validate-generated.ts -- Validate one expert-generated article against its
 * case + the article gate rules + the pairing contract.
 *
 * Hard-fails on: schema/length/register/jargon/tags/slots/minor/medical, and
 * on case-direction discrepancy (strength adjective missing, yongshin element
 * missing, or a false "채워 준다" claim when nameReinforce=none). A failing case
 * is rejected and re-generated by the harness.
 */
import type { GenerationCase } from './case-schema.js';
import { validatePlainTextQuality } from './text-quality-rules.js';

export interface GeneratedArticle {
  summary: string;
  hook?: string;
  body: string[];
  expert: string[];
  livingTips: string[];
  cautions: string[];
}

const JARGON: readonly string[] = [
  '오행', '용신', '희신', '기신', '구신', '격국', '십성', '십신', '정재', '편재', '재성',
  '편관', '식신', '식상', '겁재', '비겁', '신살', '상생', '상극', '조후', '대운',
  '득령', '득지', '득세', '원형이정', '역마', '도화', '홍염', '문창귀인', '학당',
];
const MINOR_BANNED: readonly string[] = ['연애', '결혼', '배우자', '투자', '보증', '전성기', '음주', '술자리', '이혼'];
const SLOT_NAMES = new Set(['periodLabel', 'dayMasterName', 'yongshinName', 'currentSeasonName', 'strengthPlain', 'dayMasterCount', 'yongshinCount']);
const JOSA = new Set(['이가', '은는', '을를', '과와', '으로로', '이라라']);
const SLOT_RE = /\{\{([^{}]*)\}\}/gu;
const TAG_RE = /#\{([^{}]*)\}/gu;

function approxRender(t: string): string {
  return t
    .replace(/\{\{periodLabel(?::[가-힣]+)?\}\}/gu, '이번 주')
    .replace(/\{\{strengthPlain\}\}/gu, '아주 단단한')
    .replace(/\{\{[A-Za-z]+:([가-힣]+)\}\}/gu, '나무가')
    .replace(/\{\{[A-Za-z]+\}\}/gu, '나무')
    .replace(/#\{[A-Za-z_][A-Za-z0-9_]*\}/gu, '#용신');
}
function cp(s: string): number { return [...s].length; }
function sentences(s: string): string[] { return s.split(/(?<=[.!?…])\s+|(?<=요)\s+|(?<=죠)\s+/u).map((x) => x.trim()).filter(Boolean); }
function haeyoche(s: string): boolean { return /(요|죠|에요|예요|해요|이에요)[.!?…]?$/u.test(s.trim()); }
const FORMAL = /(습니다|합니다|입니다|십시오|이다|한다|된다)[.!?…]?$/u;

function slotViolations(text: string): string[] {
  const out: string[] = [];
  for (const m of text.matchAll(SLOT_RE)) {
    const [name, josa, ...rest] = m[1].split(':');
    if (rest.length || !SLOT_NAMES.has(name)) out.push(`slot-invalid {{${m[1]}}}`);
    else if (josa !== undefined && !JOSA.has(josa)) out.push(`slot-josa {{${m[1]}}}`);
  }
  return out;
}

function dayMasterSlotStyleViolations(text: string): string[] {
  return /\{\{dayMasterName\}\}(?:은|는|이|가|을|를)/u.test(text)
    ? ['dayMasterName-direct-josa']
    : [];
}

const STRENGTH_PLAIN_PATTERNS: Readonly<Record<string, readonly RegExp[]>> = {
  balanced: [
    /(?:흐름|바탕|감정선|기류|상태|관계|리듬|기복|균형).{0,18}고른/u,
    /고른.{0,18}(?:흐름|바탕|감정선|기류|상태|관계|리듬|기복|균형)/u,
    /균형(?:이|은|을|감|적| 있게| 잡힌| 잡혀|을 유지|을 지키)/u,
    /한쪽으로.{0,12}(?:치우치|쏠리)지/u,
    /기복(?:이|은)?\s*(?:크지|적|덜|작)/u,
    /(?:안정감|안정적|안정된|평탄|완만|무난|차분한 흐름|흔들림이 크지)/u,
  ],
  strong: [
    /단단/u,
    /힘(?:이|을)?\s*(?:실리|붙|강하|넘치|앞서|버티)/u,
    /(?:추진력|주도권|기세|탄탄|적극성|밀어붙|밀고 나가|앞서가|강한 흐름|강하게)/u,
  ],
  weak: [
    /여린/u,
    /힘(?:이|을)?\s*(?:약하|빠지|부족|흩어지)/u,
    /(?:쉽게 흔들|흔들리기 쉬|무리하면 지치|버겁|소모가 크|부담이 커|보완|받쳐(?:야|주|줄)|채우고|다져야|기반을 다지)/u,
  ],
};

function hasStrengthPlainEvidence(text: string, c: GenerationCase): boolean {
  const normalized = text.replace(/\s+/gu, ' ').trim();
  const patterns = STRENGTH_PLAIN_PATTERNS[c.gangyak] ?? [];
  if (patterns.some((pattern) => pattern.test(normalized))) return true;

  // Fallback for future manifest values: require the manifest's own plain
  // signal only when no semantic pattern is defined for that strength axis.
  return patterns.length === 0 && normalized.includes(c.spec.strengthPlain);
}

const BODY_MIN_TOTAL = 60 * 8;

export function validateGenerated(a: GeneratedArticle, c: GenerationCase): { ok: boolean; violations: string[] } {
  const v: string[] = [];
  const s = c.spec;

  // -- schema shape --
  if (!Array.isArray(a.body) || a.body.length < 8 || a.body.length > 9) v.push(`body count ${a.body?.length}`);
  if (!Array.isArray(a.expert) || a.expert.length < 1 || a.expert.length > 2) v.push(`expert count ${a.expert?.length}`);
  if (!Array.isArray(a.livingTips) || a.livingTips.length < 2 || a.livingTips.length > 3) v.push(`tips count ${a.livingTips?.length}`);
  if (!Array.isArray(a.cautions) || a.cautions.length < 1 || a.cautions.length > 2) v.push(`cautions count ${a.cautions?.length}`);
  if (v.length) return { ok: false, violations: v };

  // -- summary / hook --
  const sum = approxRender(a.summary).trim();
  if (cp(sum) > 60) v.push(`summary ${cp(sum)}자>60`);
  if (sentences(sum).length !== 1) v.push('summary not 1 sentence');
  if (!haeyoche(sum) || FORMAL.test(sum)) v.push('summary register');
  v.push(...dayMasterSlotStyleViolations(a.summary).map((m) => `summary ${m}`));
  if (a.hook && cp(approxRender(a.hook)) > 24) v.push('hook >24');
  if (a.hook) v.push(...dayMasterSlotStyleViolations(a.hook).map((m) => `hook ${m}`));

  // -- body --
  let bodyTotal = 0;
  a.body.forEach((p, i) => {
    const r = approxRender(p); bodyTotal += cp(r);
    if (cp(r) > 220) v.push(`body[${i}] ${cp(r)}자`);
    const ss = sentences(r);
    if (ss.length < 1 || ss.length > 4) v.push(`body[${i}] ${ss.length}문장`);
    ss.forEach((x) => { if (FORMAL.test(x)) v.push(`body[${i}] 격식체`); else if (!haeyoche(x)) v.push(`body[${i}] 어미`); });
    v.push(...slotViolations(p).map((m) => `body[${i}] ${m}`));
    v.push(...dayMasterSlotStyleViolations(p).map((m) => `body[${i}] ${m}`));
  });
  if (bodyTotal < BODY_MIN_TOTAL || bodyTotal > 1500) v.push(`body total ${bodyTotal}자`);

  // -- expert + tags --
  const tags = new Set<string>();
  a.expert.forEach((p, i) => {
    for (const m of p.matchAll(TAG_RE)) tags.add(m[1]);
    v.push(...slotViolations(p).map((m) => `expert[${i}] ${m}`));
    v.push(...dayMasterSlotStyleViolations(p).map((m) => `expert[${i}] ${m}`));
  });
  if (tags.size < 2 || tags.size > 6) v.push(`expert tags ${tags.size} (2~6)`);

  // -- tips / cautions --
  a.livingTips.forEach((t, i) => {
    if (cp(approxRender(t)) > 30) v.push(`tip[${i}] >30`);
    v.push(...slotViolations(t).map((m) => `tip[${i}] ${m}`));
    v.push(...dayMasterSlotStyleViolations(t).map((m) => `tip[${i}] ${m}`));
  });
  a.cautions.forEach((t, i) => {
    if (cp(approxRender(t)) > 44) v.push(`caution[${i}] >44`);
    v.push(...slotViolations(t).map((m) => `caution[${i}] ${m}`));
    v.push(...dayMasterSlotStyleViolations(t).map((m) => `caution[${i}] ${m}`));
  });

  // -- plain-tier jargon (general tier only) --
  const general = [a.summary, a.hook ?? '', ...a.body, ...a.livingTips, ...a.cautions].join('\n');
  for (const term of JARGON) if (general.includes(term)) v.push(`jargon-in-general '${term}'`);
  const allTextForMeta = [a.summary, a.hook ?? '', ...a.body, ...a.expert, ...a.livingTips, ...a.cautions].join('\n');
  if (allTextForMeta.includes('독자')) v.push("meta-reader-word '독자'");

  // -- text quality: josa/run-on/formal fragments, code identifiers, burned
  //    phrases, generic frames (docs/PLAN_PR1_GENERATED_TEXT_QUALITY.md §4) --
  for (const violation of validatePlainTextQuality(a)) v.push(`${violation.rule}: ${violation.detail}`);

  // -- medical / minor --
  const all = [a.summary, a.hook ?? '', ...a.body, ...a.expert, ...a.livingTips, ...a.cautions].join('\n');
  if (all.includes('검진')) v.push('medical 검진');
  if (s.audienceSafety === 'minor') for (const w of MINOR_BANNED) if (all.includes(w)) v.push(`minor '${w}'`);

  return { ok: v.length === 0, violations: v };
}
