/**
 * validate-generated.ts -- Validate one expert-generated article against its
 * case + the article gate rules + the pairing contract.
 *
 * Hard-fails on: schema/length/register/jargon/tags/slots/minor/medical, and
 * on case-direction discrepancy (strength adjective missing, yongshin element
 * missing, or a false "채워 준다" claim when nameReinforce=none). A failing case
 * is rejected and re-generated by the harness.
 */
import type { GenerationCase } from './case-schema.js';
import { validatePlainTextQuality } from './text-quality-rules.js';

export interface GeneratedArticle {
  summary: string;
  hook?: string;
  body: string[];
  expert: string[];
  livingTips: string[];
  cautions: string[];
}

const JARGON: readonly string[] = [
  '오행', '용신', '희신', '기신', '구신', '격국', '십성', '십신', '정재', '편재', '재성',
  '편관', '식신', '식상', '겁재', '비겁', '신살', '상생', '상극', '조후', '대운',
  '득령', '득지', '득세', '원형이정', '역마', '도화', '홍염', '문창귀인', '학당',
];
const MINOR_BANNED: readonly string[] = ['연애', '결혼', '배우자', '투자', '보증', '전성기', '음주', '술자리', '이혼'];
const SLOT_NAMES = new Set(['periodLabel', 'dayMasterName', 'yongshinName', 'currentSeasonName', 'strengthPlain', 'dayMasterCount', 'yongshinCount']);
const JOSA = new Set(['이가', '은는', '을를', '과와', '으로로', '이라라']);
const SLOT_RE = /\{\{([^{}]*)\}\}/gu;
const TAG_RE = /#\{([^{}]*)\}/gu;

function approxRender(t: string): string {
  return t
    .replace(/\{\{periodLabel(?::[가-힣]+)?\}\}/gu, '이번 주')
    .replace(/\{\{strengthPlain\}\}/gu, '아주 단단한')
    .replace(/\{\{[A-Za-z]+:([가-힣]+)\}\}/gu, '나무가')
    .replace(/\{\{[A-Za-z]+\}\}/gu, '나무')
    .replace(/#\{[A-Za-z_][A-Za-z0-9_]*\}/gu, '#용신');
}
function cp(s: string): number { return [...s].length; }
function sentences(s: string): string[] { return s.split(/(?<=[.!?…])\s+|(?<=요)\s+|(?<=죠)\s+/u).map((x) => x.trim()).filter(Boolean); }
function haeyoche(s: string): boolean { return /(요|죠|에요|예요|해요|이에요)[.!?…]?$/u.test(s.trim()); }
const FORMAL = /(습니다|합니다|입니다|십시오|이다|한다|된다)[.!?…]?$/u;

function slotViolations(text: string): string[] {
  const out: string[] = [];
  for (const m of text.matchAll(SLOT_RE)) {
    const [name, josa, ...rest] = m[1].split(':');
    if (rest.length || !SLOT_NAMES.has(name)) out.push(`slot-invalid {{${m[1]}}}`);
    else if (josa !== undefined && !JOSA.has(josa)) out.push(`slot-josa {{${m[1]}}}`);
  }
  return out;
}

const STRENGTH_PLAIN_PATTERNS: Readonly<Record<string, readonly RegExp[]>> = {
  balanced: [
    /(?:흐름|바탕|감정선|기류|상태|관계|리듬|기복|균형).{0,18}고른/u,
    /고른.{0,18}(?:흐름|바탕|감정선|기류|상태|관계|리듬|기복|균형)/u,
    /균형(?:이|은|을|감|적| 있게| 잡힌| 잡혀|을 유지|을 지키)/u,
    /한쪽으로.{0,12}(?:치우치|쏠리)지/u,
    /기복(?:이|은)?\s*(?:크지|적|덜|작)/u,
    /(?:안정감|안정적|안정된|평탄|완만|무난|차분한 흐름|흔들림이 크지)/u,
  ],
  strong: [
    /단단/u,
    /힘(?:이|을)?\s*(?:실리|붙|강하|넘치|앞서|버티)/u,
    /(?:추진력|주도권|기세|탄탄|적극성|밀어붙|밀고 나가|앞서가|강한 흐름|강하게)/u,
  ],
  weak: [
    /여린/u,
    /힘(?:이|을)?\s*(?:약하|빠지|부족|흩어지)/u,
    /(?:쉽게 흔들|흔들리기 쉬|무리하면 지치|버겁|소모가 크|부담이 커|보완|받쳐(?:야|주|줄)|채우고|다져야|기반을 다지)/u,
  ],
};

function hasStrengthPlainEvidence(text: string, c: GenerationCase): boolean {
  const normalized = text.replace(/\s+/gu, ' ').trim();
  const patterns = STRENGTH_PLAIN_PATTERNS[c.gangyak] ?? [];
  if (patterns.some((pattern) => pattern.test(normalized))) return true;

  // Fallback for future manifest values: require the manifest's own plain
  // signal only when no semantic pattern is defined for that strength axis.
  return patterns.length === 0 && normalized.includes(c.spec.strengthPlain);
}

export function validateGenerated(a: GeneratedArticle, c: GenerationCase): { ok: boolean; violations: string[] } {
  const v: string[] = [];
  const s = c.spec;

  // -- schema shape --
  if (!Array.isArray(a.body) || a.body.length < 3 || a.body.length > 4) v.push(`body count ${a.body?.length}`);
  if (!Array.isArray(a.expert) || a.expert.length < 1 || a.expert.length > 2) v.push(`expert count ${a.expert?.length}`);
  if (!Array.isArray(a.livingTips) || a.livingTips.length < 2 || a.livingTips.length > 3) v.push(`tips count ${a.livingTips?.length}`);
  if (!Array.isArray(a.cautions) || a.cautions.length < 1 || a.cautions.length > 2) v.push(`cautions count ${a.cautions?.length}`);
  if (v.length) return { ok: false, violations: v };

  // -- summary / hook --
  const sum = approxRender(a.summary).trim();
  if (cp(sum) > 60) v.push(`summary ${cp(sum)}자>60`);
  if (sentences(sum).length !== 1) v.push('summary not 1 sentence');
  if (!haeyoche(sum) || FORMAL.test(sum)) v.push('summary register');
  if (a.hook && cp(approxRender(a.hook)) > 24) v.push('hook >24');

  // -- body --
  let bodyTotal = 0;
  a.body.forEach((p, i) => {
    const r = approxRender(p); bodyTotal += cp(r);
    if (cp(r) < 80 || cp(r) > 240) v.push(`body[${i}] ${cp(r)}자`);
    const ss = sentences(r);
    if (ss.length < 2 || ss.length > 5) v.push(`body[${i}] ${ss.length}문장`);
    ss.forEach((x) => { if (FORMAL.test(x)) v.push(`body[${i}] 격식체`); else if (!haeyoche(x)) v.push(`body[${i}] 어미`); });
    v.push(...slotViolations(p).map((m) => `body[${i}] ${m}`));
  });
  if (bodyTotal < 350 || bodyTotal > 800) v.push(`body total ${bodyTotal}자`);

  // -- expert + tags --
  const tags = new Set<string>();
  a.expert.forEach((p, i) => {
    const r = approxRender(p);
    if (cp(r) < 100 || cp(r) > 380) v.push(`expert[${i}] ${cp(r)}자`);
    for (const m of p.matchAll(TAG_RE)) tags.add(m[1]);
    v.push(...slotViolations(p).map((m) => `expert[${i}] ${m}`));
  });
  if (tags.size < 2 || tags.size > 6) v.push(`expert tags ${tags.size} (2~6)`);

  // -- tips / cautions --
  a.livingTips.forEach((t, i) => { if (cp(approxRender(t)) > 30) v.push(`tip[${i}] >30`); v.push(...slotViolations(t).map((m) => `tip[${i}] ${m}`)); });
  a.cautions.forEach((t, i) => { if (cp(approxRender(t)) > 44) v.push(`caution[${i}] >44`); v.push(...slotViolations(t).map((m) => `caution[${i}] ${m}`)); });

  // -- plain-tier jargon (general tier only) --
  const general = [a.summary, a.hook ?? '', ...a.body, ...a.livingTips, ...a.cautions].join('\n');
  for (const term of JARGON) if (general.includes(term)) v.push(`jargon-in-general '${term}'`);

  // -- text quality: josa/run-on/formal fragments, code identifiers, burned
  //    phrases, generic frames (docs/PLAN_PR1_GENERATED_TEXT_QUALITY.md §4) --
  for (const violation of validatePlainTextQuality(a)) v.push(`${violation.rule}: ${violation.detail}`);

  // -- deadline safety: a paid service must not advise deferring/ignoring a REAL
  //    deadline on the strength of fortune ("마감은 기한만 확인하고 손 떼기" /
  //    "마감을 넉넉히 미뤄"). Safe low-band advice shrinks scope or does the
  //    minimum required part — it does not tell the reader to skip obligations.
  const plainSafety = [a.summary, ...a.body, ...a.livingTips, ...a.cautions].join('\n');
  const DEADLINE_UNSAFE = /기한만 확인[^.!?]{0,25}(손\s?대지 않|손\s?떼|안 건드|건드리지 않|보지)|마감[^.!?]{0,15}(넉넉히 미|미뤄 두|미뤄서|뒤로 미|덮어)/u;
  if (DEADLINE_UNSAFE.test(plainSafety)) v.push('마감 방치 조언(안전 위반)');

  // -- medical / minor --
  const all = [a.summary, a.hook ?? '', ...a.body, ...a.expert, ...a.livingTips, ...a.cautions].join('\n');
  if (all.includes('검진')) v.push('medical 검진');
  if (s.audienceSafety === 'minor') for (const w of MINOR_BANNED) if (all.includes(w)) v.push(`minor '${w}'`);

  // -- CASE DIRECTION CONSISTENCY (pairing, v2) --
  // The class fixes 강약. The plain tier must show that direction by meaning,
  // not by mechanically injecting one fixed adjective.
  const strengthPlainText = [a.summary, a.hook ?? '', ...a.body].join('\n');
  if (!hasStrengthPlainEvidence(strengthPlainText, c)) {
    v.push(`강약 평문 방향 미반영(${c.gangyak}/${s.strengthTerm})`);
  }
  // honesty: neutral and adverse names must not positively claim they fill/boost
  // the needed element — but the two fail differently, so they are checked apart.
  if (c.nameEffect === 'neutral') {
    // NEUTRAL: the name neither pushes nor blocks. ANY positive-benefit claim
    // (verb OR noun form: 덕에·뒷심·보태는·받쳐 주는…) is a violation unless the
    // sentence directly disclaims the name's role. A stray 않/보다 elsewhere no
    // longer exempts (that hole let 10-inseong-neutral read as a boost).
    const POS = /이름[은는이가]?[^.!?]{0,20}(채워 주|크게 담|크게 채|보강|덕에|덕분|뒷심|보태(는|어 주|아 주)|받쳐 주|실어 주|더해 주는|힘을 보태|힘이 붙|밀어 주)/u;
    const DISC = /(주진 않|주지(는|를)? 않|주지도[^.!?]{0,15}(않|없)|정해 주진|끌어 주진|잡아 주진|밀어 주지|밀지(도)? 않|막지(도)? 않|발목(을)? (잡|붙)|담고 있진 않|직접 (담|채우|밀|끌)|대신[^.!?]{0,10}(정해|잡아|끌어|채워|붙)|이름이 아니라|이름 덕(이|은|만)? 아니|가감(하지|은|을)? ?(않|없)|밀거나 막|특별히 (밀|막)|앞에서 (끌|밀)어 주진)/u;
    for (const sent of all.split(/(?<=[.!?요죠])\s+/u)) {
      if (sent.includes('이름') && POS.test(sent) && !DISC.test(sent)) {
        v.push('nameEffect=neutral 이름 긍정효과 서술(정직성 위반)');
        break;
      }
    }
  } else if (c.nameEffect === 'adverse') {
    // ADVERSE: honest framing = the name adds to the ALREADY-FULL side and the
    // deficit is filled by daily habits ("보태는 몫이 이미 찬 쪽에 실린"). Only a
    // claim that the name fills the NEEDED element is dishonest; the excess-side
    // framing (이미 찬/넉넉/실린/담는 쪽) exempts.
    const FILL = /(채워 주|채워 준다|채워 줘|크게 담|크게 채|보강해 주|보강해 준다)/u;
    const NEG = /(않|없|아니|보다|대신|뿐|못|마세|마요|말자|말라|말고|기보다|건 아|리 없|이미 (찬|넉넉|과)|넉넉한 쪽|찬 쪽|찬 자리|실린|담는 쪽|얹)/u;
    for (const sent of all.split(/(?<=[.!?요죠])\s+/u)) {
      if (sent.includes('이름') && FILL.test(sent) && !NEG.test(sent)) {
        v.push('nameEffect=adverse 이름 채움 주장(정직성 위반)');
        break;
      }
    }
  }

  return { ok: v.length === 0, violations: v };
}
