/* Generated by tools/engine-build-manifest.mjs. Do not edit. */

export const ENGINE_BUILD_IDENTITY_V1 = Object.freeze({
  "schemaVersion": "namespring.engine-build-input-manifest.v1",
  "authority": "build-time-artifact-identity-only",
  "completeness": "declared-tracked-build-input-scope-not-execution-reproducibility",
  "aggregateDigest": "sha256:1cef542bc0eb7f47e798e87f2a031a6139f9739fe636b53f27316347d815fff1",
  "rulesetDigest": "sha256:2c55f5ea2d49ed7911762cda98ee1aa43d901c4eab241e421e6f8103ee29b2a0",
  "dataDigest": "sha256:f457cd5126bee2e68ff40681971ccd4fb116065b8da1579be6405a9c755e2e78",
  "manifestFileCount": 397
} as const);
