/* Generated by tools/engine-build-manifest.mjs. Do not edit. */

export const ENGINE_BUILD_IDENTITY_V1 = Object.freeze({
  "schemaVersion": "namespring.engine-build-input-manifest.v1",
  "authority": "build-time-artifact-identity-only",
  "completeness": "declared-tracked-build-input-scope-not-execution-reproducibility",
  "aggregateDigest": "sha256:b3bd38a39b75480ef07da5c78c44a71623e03d308f0225c2000255d66b071303",
  "rulesetDigest": "sha256:b74cf187fd03912d23f8aeece5221fedaa2e1cf41a73108515b956ec493cda60",
  "dataDigest": "sha256:f457cd5126bee2e68ff40681971ccd4fb116065b8da1579be6405a9c755e2e78",
  "manifestFileCount": 381
} as const);
